In [3]:
import pandas as pd
db= pd.read_csv('C:\\Users\\Nehanth\\Desktop\\DSP\\diabetes.csv')
print(db.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6
1            1       85             66             29        0  26.6
2            8      183             64              0        0  23.3
3            1       89             66             23       94  28.1
4            0      137             40             35      168  43.1

   DiabetesPedigreeFunction  Age  Outcome
0                     0.627   50        1
1                     0.351   31        0
2                     0.672   32        1
3                     0.167   21        0
4                     2.288   33        1

In [4]:
print(db.head(5))

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6
1            1       85             66             29        0  26.6
2            8      183             64              0        0  23.3
3            1       89             66             23       94  28.1
4            0      137             40             35      168  43.1

   DiabetesPedigreeFunction  Age  Outcome
0                     0.627   50        1
1                     0.351   31        0
2                     0.672   32        1
3                     0.167   21        0
4                     2.288   33        1

In [5]:
print(db.ndim)

2

In [6]:
print(db.shape)

(768, 9)

In [7]:
print(db.axes)

[RangeIndex(start=0, stop=768, step=1), Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')]

In [8]:
print(db.loc[:,'BloodPressure'])

0      72
1      66
2      64
3      66
4      40
       ..
763    76
764    70
765    72
766    60
767    70
Name: BloodPressure, Length: 768, dtype: int64

In [11]:
print(db.loc[:,'Age'])

0      50
1      31
2      32
3      21
4      33
       ..
763    63
764    27
765    30
766    47
767    23
Name: Age, Length: 768, dtype: int64

In [14]:
newdb= db.loc[:,['Pregnancies', 'Glucose', 'Insulin', 'Age']]
print(newdb.head())

   Pregnancies  Glucose  Insulin  Age
0            6      148        0   50
1            1       85        0   31
2            8      183        0   32
3            1       89       94   21
4            0      137      168   33

In [16]:
file_name = "C:\\Users\\Nehanth\\Desktop\\DSP\\diabetes1.csv"
newdb. to_csv(file_name, sep=',', encoding='utf-8')

In [20]:
print(db.iloc[:,[2,3,4,5]])

     BloodPressure  SkinThickness  Insulin   BMI
0               72             35        0  33.6
1               66             29        0  26.6
2               64              0        0  23.3
3               66             23       94  28.1
4               40             35      168  43.1
..             ...            ...      ...   ...
763             76             48      180  32.9
764             70             27        0  36.8
765             72             23      112  26.2
766             60              0        0  30.1
767             70             31        0  30.4

[768 rows x 4 columns]

In [26]:
db[db.Glucose>195]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
8,2,197,70,45,543,30.5,0.158,53,1
22,7,196,90,0,0,39.8,0.451,41,1
206,8,196,76,29,280,37.5,0.605,57,1
228,4,197,70,39,744,36.7,2.329,31,0
359,1,196,76,36,249,36.5,0.875,29,1
408,8,197,74,0,0,25.9,1.191,39,1
561,0,198,66,32,274,41.3,0.502,28,1
579,2,197,70,99,0,34.7,0.575,62,1
661,1,199,76,43,0,42.9,1.394,22,1

In [30]:
db[(db.Age>40) & (db.Glucose>195)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
8,2,197,70,45,543,30.5,0.158,53,1
22,7,196,90,0,0,39.8,0.451,41,1
206,8,196,76,29,280,37.5,0.605,57,1
579,2,197,70,99,0,34.7,0.575,62,1

In [32]:
db[(db.Pregnancies>5)&(db.Glucose>190)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
22,7,196,90,0,0,39.8,0.451,41,1
185,7,194,68,28,0,35.9,0.745,41,1
206,8,196,76,29,280,37.5,0.605,57,1
319,6,194,78,0,0,23.5,0.129,59,1
408,8,197,74,0,0,25.9,1.191,39,1
489,8,194,80,0,0,26.1,0.551,67,0
498,7,195,70,33,145,25.1,0.163,55,1
675,6,195,70,0,0,30.9,0.328,31,1

In [33]:
numbers = [1,0]
db[db.Outcome.isin(numbers)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [34]:
print(db.describe())

       Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000
mean      3.845052  120.894531      69.105469      20.536458   79.799479
std       3.369578   31.972618      19.355807      15.952218  115.244002
min       0.000000    0.000000       0.000000       0.000000    0.000000
25%       1.000000   99.000000      62.000000       0.000000    0.000000
50%       3.000000  117.000000      72.000000      23.000000   30.500000
75%       6.000000  140.250000      80.000000      32.000000  127.250000
max      17.000000  199.000000     122.000000      99.000000  846.000000

              BMI  DiabetesPedigreeFunction         Age     Outcome
count  768.000000                768.000000  768.000000  768.000000
mean    31.992578                  0.471876   33.240885    0.348958
std      7.884160                  0.331329   11.760232    0.476951
min      0.000000                  0.078000   21.000000    0.000000
25%     27.300000                  0.243750   24.000000    0.000000
50%     32.000000                  0.372500   29.000000    0.000000
75%     36.600000                  0.626250   41.000000    1.000000
max     67.100000                  2.420000   81.000000    1.000000

In [35]:
db.sort_index()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [36]:
db.sort_index(ascending=False)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
767,1,93,70,31,0,30.4,0.315,23,0
766,1,126,60,0,0,30.1,0.349,47,1
765,5,121,72,23,112,26.2,0.245,30,0
764,2,122,70,27,0,36.8,0.340,27,0
763,10,101,76,48,180,32.9,0.171,63,0
...,...,...,...,...,...,...,...,...,...
4,0,137,40,35,168,43.1,2.288,33,1
3,1,89,66,23,94,28.1,0.167,21,0
2,8,183,64,0,0,23.3,0.672,32,1
1,1,85,66,29,0,26.6,0.351,31,0
0,6,148,72,35,0,33.6,0.627,50,1

In [38]:
db.sort_values(by='Age')

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
255,1,113,64,35,0,33.6,0.543,21,1
60,2,84,0,0,0,0.0,0.304,21,0
102,0,125,96,0,0,22.5,0.262,21,0
182,1,0,74,20,23,27.7,0.299,21,0
623,0,94,70,27,115,43.5,0.347,21,0
...,...,...,...,...,...,...,...,...,...
123,5,132,80,0,0,26.8,0.186,69,0
684,5,136,82,0,0,0.0,0.640,69,0
666,4,145,82,18,0,32.5,0.235,70,1
453,2,119,0,0,0,19.6,0.832,72,0
459,9,134,74,33,60,25.9,0.460,81,0

In [39]:
db.sort_values(by="Age",ascending=False)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
459,9,134,74,33,60,25.9,0.460,81,0
453,2,119,0,0,0,19.6,0.832,72,0
666,4,145,82,18,0,32.5,0.235,70,1
123,5,132,80,0,0,26.8,0.186,69,0
684,5,136,82,0,0,0.0,0.640,69,0
...,...,...,...,...,...,...,...,...,...
240,1,91,64,24,0,29.2,0.192,21,0
136,0,100,70,26,50,30.8,0.597,21,0
382,1,109,60,8,182,25.4,0.947,21,0
392,1,131,64,14,415,23.7,0.389,21,0
271,2,108,62,32,56,25.2,0.128,21,0

In [41]:
dbx=db[db.Age>80]
dbx.shape

(1, 9)

In [42]:
db.DiabetesPedigreeFunction.min()

0.078

In [43]:
db.DiabetesPedigreeFunction.max()

2.42

In [46]:
db.value_counts('Age')

Age
22    72
21    63
25    48
24    46
23    38
28    35
26    33
27    32
29    29
31    24
41    22
30    21
37    19
42    18
33    17
38    16
36    16
32    16
45    15
34    14
40    13
43    13
46    13
39    12
35    10
52     8
44     8
50     8
51     8
58     7
54     6
47     6
53     5
60     5
49     5
57     5
48     5
66     4
62     4
63     4
55     4
59     3
56     3
65     3
67     3
61     2
69     2
64     1
68     1
70     1
72     1
81     1
dtype: int64

In [47]:
db.groupby('Age').sum()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Outcome
Age,,,,,,,,
21,68,6824,4154,1219,4639,1752.5,27.331,5
22,112,7791,4588,1475,5363,2124.7,31.005,11
23,60,4240,2444,850,4485,1197.1,16.666,7
24,87,5423,2988,1193,4049,1498.2,18.104,8
25,85,5284,2864,1150,3979,1533.3,28.824,14
26,65,3901,2118,781,2999,1152.2,13.644,8
27,82,3689,2352,588,2020,1022.4,15.096,8
28,106,4197,2391,827,3311,1177.5,16.087,10
29,96,3694,1979,609,2575,972.7,11.858,13
30,76,2568,1362,397,1736,630.7,7.712,6
31,93,3047,1545,480,2668,816.4,14.150,13
32,71,1861,1121,291,573,517.1,9.812,9
33,69,2089,1116,369,1455,549.7,12.481,10
34,82,1846,1036,262,2073,436.3,9.098,4
35,50,1214,756,226,750,337.8,4.540,5
36,83,2119,1106,307,1053,507.5,7.566,10
37,100,2473,1443,348,1126,609.5,7.878,6
38,110,1938,1138,314,536,569.1,6.623,10
39,89,1521,872,313,869,383.8,7.271,3
40,81,1702,900,315,940,436.0,4.889,6
41,143,2840,1487,383,854,775.7,8.718,13
42,124,1972,1321,346,1103,629.7,6.984,7
43,101,1729,1020,362,1627,479.6,5.861,11
44,58,995,494,37,258,273.3,5.347,5
45,110,1968,1246,309,467,524.4,7.447,8
46,83,1377,988,314,1460,448.8,5.549,7
47,50,822,470,87,295,207.4,2.132,4
48,44,538,392,117,260,149.9,2.284,1
49,38,765,407,108,276,160.1,3.060,3
50,54,1106,626,128,211,249.8,3.761,5
51,69,1181,676,175,1035,271.8,4.922,5
52,37,1064,652,107,756,267.8,4.043,7
53,27,790,395,106,915,152.5,2.753,4
54,42,842,536,53,366,184.8,2.793,4
55,22,563,281,65,335,108.1,0.906,1
56,24,295,229,97,207,95.1,2.810,2
57,44,689,384,48,390,148.5,3.520,1
58,50,946,548,135,1175,227.0,3.883,3
59,7,520,222,50,846,80.9,0.758,2
60,30,732,400,100,821,143.7,2.184,2
61,11,288,152,33,190,60.0,1.226,1
62,15,558,286,116,0,115.8,2.262,2
63,22,533,312,94,180,123.1,0.997,0
64,8,120,78,0,0,25.0,0.409,0
65,10,411,236,37,0,94.8,0.777,0
66,20,628,344,0,0,121.5,1.634,2
67,12,397,218,0,0,86.3,1.806,1
68,8,91,82,0,0,35.6,0.587,0
69,10,268,162,0,0,26.8,0.826,0
70,4,145,82,18,0,32.5,0.235,1
72,2,119,0,0,0,19.6,0.832,0
81,9,134,74,33,60,25.9,0.460,0

In [48]:
db.groupby('Age').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Outcome
Age,,,,,,,,
21,1.079365,108.317460,65.936508,19.349206,73.634921,27.817460,0.433825,0.079365
22,1.555556,108.208333,63.722222,20.486111,74.486111,29.509722,0.430625,0.152778
23,1.578947,111.578947,64.315789,22.368421,118.026316,31.502632,0.438579,0.184211
24,1.891304,117.891304,64.956522,25.934783,88.021739,32.569565,0.393565,0.173913
25,1.770833,110.083333,59.666667,23.958333,82.895833,31.943750,0.600500,0.291667
26,1.969697,118.212121,64.181818,23.666667,90.878788,34.915152,0.413455,0.242424
27,2.562500,115.281250,73.500000,18.375000,63.125000,31.950000,0.471750,0.250000
28,3.028571,119.914286,68.314286,23.628571,94.600000,33.642857,0.459629,0.285714
29,3.310345,127.379310,68.241379,21.000000,88.793103,33.541379,0.408897,0.448276
30,3.619048,122.285714,64.857143,18.904762,82.666667,30.033333,0.367238,0.285714
31,3.875000,126.958333,64.375000,20.000000,111.166667,34.016667,0.589583,0.541667
32,4.437500,116.312500,70.062500,18.187500,35.812500,32.318750,0.613250,0.562500
33,4.058824,122.882353,65.647059,21.705882,85.588235,32.335294,0.734176,0.588235
34,5.857143,131.857143,74.000000,18.714286,148.071429,31.164286,0.649857,0.285714
35,5.000000,121.400000,75.600000,22.600000,75.000000,33.780000,0.454000,0.500000
36,5.187500,132.437500,69.125000,19.187500,65.812500,31.718750,0.472875,0.625000
37,5.263158,130.157895,75.947368,18.315789,59.263158,32.078947,0.414632,0.315789
38,6.875000,121.125000,71.125000,19.625000,33.500000,35.568750,0.413937,0.625000
39,7.416667,126.750000,72.666667,26.083333,72.416667,31.983333,0.605917,0.250000
40,6.230769,130.923077,69.230769,24.230769,72.307692,33.538462,0.376077,0.461538
41,6.500000,129.090909,67.590909,17.409091,38.818182,35.259091,0.396273,0.590909
42,6.888889,109.555556,73.388889,19.222222,61.277778,34.983333,0.388000,0.388889
43,7.769231,133.000000,78.461538,27.846154,125.153846,36.892308,0.450846,0.846154
44,7.250000,124.375000,61.750000,4.625000,32.250000,34.162500,0.668375,0.625000
45,7.333333,131.200000,83.066667,20.600000,31.133333,34.960000,0.496467,0.533333
46,6.384615,105.923077,76.000000,24.153846,112.307692,34.523077,0.426846,0.538462
47,8.333333,137.000000,78.333333,14.500000,49.166667,34.566667,0.355333,0.666667
48,8.800000,107.600000,78.400000,23.400000,52.000000,29.980000,0.456800,0.200000
49,7.600000,153.000000,81.400000,21.600000,55.200000,32.020000,0.612000,0.600000
50,6.750000,138.250000,78.250000,16.000000,26.375000,31.225000,0.470125,0.625000
51,8.625000,147.625000,84.500000,21.875000,129.375000,33.975000,0.615250,0.625000
52,4.625000,133.000000,81.500000,13.375000,94.500000,33.475000,0.505375,0.875000
53,5.400000,158.000000,79.000000,21.200000,183.000000,30.500000,0.550600,0.800000
54,7.000000,140.333333,89.333333,8.833333,61.000000,30.800000,0.465500,0.666667
55,5.500000,140.750000,70.250000,16.250000,83.750000,27.025000,0.226500,0.250000
56,8.000000,98.333333,76.333333,32.333333,69.000000,31.700000,0.936667,0.666667
57,8.800000,137.800000,76.800000,9.600000,78.000000,29.700000,0.704000,0.200000
58,7.142857,135.142857,78.285714,19.285714,167.857143,32.428571,0.554714,0.428571
59,2.333333,173.333333,74.000000,16.666667,282.000000,26.966667,0.252667,0.666667
60,6.000000,146.400000,80.000000,20.000000,164.200000,28.740000,0.436800,0.400000
61,5.500000,144.000000,76.000000,16.500000,95.000000,30.000000,0.613000,0.500000
62,3.750000,139.500000,71.500000,29.000000,0.000000,28.950000,0.565500,0.500000
63,5.500000,133.250000,78.000000,23.500000,45.000000,30.775000,0.249250,0.000000
64,8.000000,120.000000,78.000000,0.000000,0.000000,25.000000,0.409000,0.000000
65,3.333333,137.000000,78.666667,12.333333,0.000000,31.600000,0.259000,0.000000
66,5.000000,157.000000,86.000000,0.000000,0.000000,30.375000,0.408500,0.500000
67,4.000000,132.333333,72.666667,0.000000,0.000000,28.766667,0.602000,0.333333
68,8.000000,91.000000,82.000000,0.000000,0.000000,35.600000,0.587000,0.000000
69,5.000000,134.000000,81.000000,0.000000,0.000000,13.400000,0.413000,0.000000
70,4.000000,145.000000,82.000000,18.000000,0.000000,32.500000,0.235000,1.000000
72,2.000000,119.000000,0.000000,0.000000,0.000000,19.600000,0.832000,0.000000
81,9.000000,134.000000,74.000000,33.000000,60.000000,25.900000,0.460000,0.000000

In [50]:
db.groupby('Age').sum().min()

Pregnancies                  2.000
Glucose                     91.000
BloodPressure                0.000
SkinThickness                0.000
Insulin                      0.000
BMI                         19.600
DiabetesPedigreeFunction     0.235
Outcome                      0.000
dtype: float64

In [51]:
db3=db.assign(AgeBMI=(db.loc[:,'Age']/db.loc[:,'BMI'])*0.5)
print(db3.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6
1            1       85             66             29        0  26.6
2            8      183             64              0        0  23.3
3            1       89             66             23       94  28.1
4            0      137             40             35      168  43.1

   DiabetesPedigreeFunction  Age  Outcome    AgeBMI
0                     0.627   50        1  0.744048
1                     0.351   31        0  0.582707
2                     0.672   32        1  0.686695
3                     0.167   21        0  0.373665
4                     2.288   33        1  0.382831