In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

In [3]:
df = pd. read_csv("C:\\Users\\Nehanth\\Desktop\\DSP\\project\\archive\\paysim1.csv")
df.head()

,Unnamed: 0,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud
0,0,1,PAYMENT,9839.64,170136.0,160296.36,0.0,0.0,0
1,1,1,PAYMENT,1864.28,21249.0,19384.72,0.0,0.0,0
2,2,1,TRANSFER,181.00,181.0,0.00,0.0,0.0,1
3,3,1,CASH_OUT,181.00,181.0,0.00,21182.0,0.0,1
4,4,1,PAYMENT,11668.14,41554.0,29885.86,0.0,0.0,0

In [4]:
df = df.drop(columns = ['Unnamed: 0'])
df.head()

,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud
0,1,PAYMENT,9839.64,170136.0,160296.36,0.0,0.0,0
1,1,PAYMENT,1864.28,21249.0,19384.72,0.0,0.0,0
2,1,TRANSFER,181.00,181.0,0.00,0.0,0.0,1
3,1,CASH_OUT,181.00,181.0,0.00,21182.0,0.0,1
4,1,PAYMENT,11668.14,41554.0,29885.86,0.0,0.0,0

In [5]:
df = df.sample(n=500)

In [15]:
paysim_data_copy = df.copy(deep = True)
paysim_data_copy[['amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']] = paysim_data_copy[['amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']].replace(0)

In [16]:
paysim_data_copy['amount'].fillna(paysim_data_copy['amount'].mean(), inplace = True)
paysim_data_copy['oldbalanceOrg'].fillna(paysim_data_copy['amount'].mean(), inplace = True)
paysim_data_copy['newbalanceOrig'].fillna(paysim_data_copy['amount'].mean(), inplace = True)
paysim_data_copy['oldbalanceDest'].fillna(paysim_data_copy['amount'].mean(), inplace = True)
paysim_data_copy['newbalanceDest'].fillna(paysim_data_copy['amount'].mean(), inplace = True)

In [17]:
paysim_data_copy.head()

,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud
5012215,353,CASH_OUT,171291.82,5035.00,0.00,299804.87,471096.69,0
5908376,404,CASH_OUT,106672.06,20412.00,0.00,1513575.35,1620247.41,0
2748294,212,PAYMENT,3439.62,373422.65,369983.04,1513575.35,1620247.41,0
5109749,355,PAYMENT,13147.63,206645.00,193497.37,1513575.35,1620247.41,0
3660817,275,CASH_IN,241256.78,9617077.63,9858334.41,4770766.95,4529510.17,0

In [14]:
paysim_data_copy.corr()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud
step,1.000000,0.004201,0.033124,0.033336,0.090984,0.088914,NaN
amount,0.004201,1.000000,0.041043,0.050869,0.141900,0.194693,NaN
oldbalanceOrg,0.033124,0.041043,1.000000,0.999418,0.091266,0.067157,NaN
newbalanceOrig,0.033336,0.050869,0.999418,1.000000,0.089260,0.064403,NaN
oldbalanceDest,0.090984,0.141900,0.091266,0.089260,1.000000,0.996285,NaN
newbalanceDest,0.088914,0.194693,0.067157,0.064403,0.996285,1.000000,NaN
isFraud,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
X = paysim_data_copy.iloc[:,[2,3,4,5,6]]
y = paysim_data_copy.iloc[:,[7]]

In [22]:
knn.score(X_train,y_train)

1.0

In [23]:


error_rate = []
# Might take some time
for i in range(1,40):
    
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    pred_i = knn.predict(X_test)
    error_rate.append(np.mean(pred_i != y_test))

C:\Users\Nehanth\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
<ipython-input-23-2d78ed4343e6>:8: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  error_rate.append(np.mean(pred_i != y_test))

ValueError: Unable to coerce to Series, length must be 1: given 167

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 1/3, random_state=42)

In [21]:
knn = KNeighborsClassifier(n_neighbors=5, algorithm = "ball_tree")
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
confusion_matrix(y_test,y_pred)
pd.crosstab(y_test, y_pred, rownames = ['True'], colnames = ['Predicted'], margins = True)

C:\Users\Nehanth\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

ValueError: Shape of passed values is (1, 2), indices imply (167, 2)